version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nakama_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nakama_user
      POSTGRES_PASSWORD: nakama_password
      POSTGRES_DB: nakama_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
